run:
  timeout: 5m
issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - funlen
    - gofumpt
    - interfacer
    - lll
    - maligned
    - scopelint
    - testpackage
    - wrapcheck
