run:
  timeout: 5m
issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
linters:
  enable-all: true
  disable:
    - lll
    - funlen
    - gofumpt
    - gci
    - ifshort
    - nlreturn
    - testpackage
    - exhaustivestruct
    - wrapcheck
    - paralleltest
    - forbidigo
    - thelper
